import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        handwriting: ['Caveat', 'cursive'],
        casual: ['Patrick Hand', 'cursive'],
        body: ['Nunito', 'sans-serif'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        paper: "hsl(var(--paper))",
        ink: "hsl(var(--ink))",
        highlight: "hsl(var(--highlight))",
        sticky: "hsl(var(--sticky))",
        doodle: "hsl(var(--doodle))",
        spiral: "hsl(var(--spiral))",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        hand: "255px 15px 225px 15px/15px 225px 15px 255px",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0", transform: "translateY(20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "slide-in-left": {
          from: { opacity: "0", transform: "translateX(-30px)" },
          to: { opacity: "1", transform: "translateX(0)" },
        },
        "slide-in-right": {
          from: { opacity: "0", transform: "translateX(30px)" },
          to: { opacity: "1", transform: "translateX(0)" },
        },
        "pop-in": {
          "0%": { opacity: "0", transform: "scale(0.8) rotate(-5deg)" },
          "70%": { transform: "scale(1.05) rotate(2deg)" },
          "100%": { opacity: "1", transform: "scale(1) rotate(0)" },
        },
        "bounce-in": {
          "0%": { opacity: "0", transform: "scale(0.3)" },
          "50%": { transform: "scale(1.05)" },
          "70%": { transform: "scale(0.9)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        "spin-slow": {
          from: { transform: "rotate(0deg)" },
          to: { transform: "rotate(360deg)" },
        },
        "spin-reverse": {
          from: { transform: "rotate(360deg)" },
          to: { transform: "rotate(0deg)" },
        },
        "pulse-glow": {
          "0%, 100%": { opacity: "1", boxShadow: "0 0 0 0 hsl(var(--accent) / 0.4)" },
          "50%": { opacity: "0.8", boxShadow: "0 0 20px 10px hsl(var(--accent) / 0)" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0) rotate(0deg)" },
          "25%": { transform: "translateY(-10px) rotate(2deg)" },
          "50%": { transform: "translateY(-5px) rotate(-1deg)" },
          "75%": { transform: "translateY(-15px) rotate(1deg)" },
        },
        "float-rotate": {
          "0%, 100%": { transform: "translateY(0) rotate(0deg)" },
          "25%": { transform: "translateY(-12px) rotate(15deg)" },
          "50%": { transform: "translateY(-6px) rotate(-10deg)" },
          "75%": { transform: "translateY(-18px) rotate(8deg)" },
        },
        "float-delayed": {
          "0%, 100%": { transform: "translateY(0) rotate(0deg)" },
          "33%": { transform: "translateY(-14px) rotate(5deg)" },
          "66%": { transform: "translateY(-8px) rotate(-3deg)" },
        },
        "pulse-float": {
          "0%, 100%": { transform: "translateY(0) scale(1)", opacity: "0.4" },
          "50%": { transform: "translateY(-8px) scale(1.2)", opacity: "0.7" },
        },
        "wiggle-slow": {
          "0%, 100%": { transform: "rotate(-3deg)" },
          "50%": { transform: "rotate(3deg)" },
        },
        "heartbeat": {
          "0%, 100%": { transform: "scale(1)" },
          "14%": { transform: "scale(1.15)" },
          "28%": { transform: "scale(1)" },
          "42%": { transform: "scale(1.15)" },
          "70%": { transform: "scale(1)" },
        },
        "bounce-horizontal": {
          "0%, 100%": { transform: "translateX(0)" },
          "50%": { transform: "translateX(10px)" },
        },
        "flash": {
          "0%, 100%": { opacity: "0.3" },
          "50%": { opacity: "0.9" },
        },
        "bounce-slow": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-5px)" },
        },
        "bounce-elastic": {
          "0%, 100%": { transform: "translateY(0) scale(1)" },
          "30%": { transform: "translateY(-20px) scale(1.1)" },
          "50%": { transform: "translateY(-10px) scale(0.95)" },
          "70%": { transform: "translateY(-15px) scale(1.05)" },
        },
        "fly": {
          "0%": { transform: "translate(0, 0) rotate(0deg)" },
          "25%": { transform: "translate(5px, -8px) rotate(5deg)" },
          "50%": { transform: "translate(10px, 0) rotate(0deg)" },
          "75%": { transform: "translate(5px, 8px) rotate(-5deg)" },
          "100%": { transform: "translate(0, 0) rotate(0deg)" },
        },
        "steam": {
          "0%, 100%": { transform: "translateY(0)", opacity: "0.5" },
          "50%": { transform: "translateY(-3px)", opacity: "1" },
        },
        "draw-line": {
          from: { strokeDasharray: "0 200" },
          to: { strokeDasharray: "200 0" },
        },
        "draw-path": {
          "0%": { strokeDasharray: "0 500", strokeDashoffset: "0" },
          "100%": { strokeDasharray: "500 0", strokeDashoffset: "0" },
        },
        "wiggle": {
          "0%, 100%": { transform: "rotate(-5deg)" },
          "50%": { transform: "rotate(5deg)" },
        },
        "shooting-star": {
          "0%": { transform: "translateX(-100px) translateY(-50px)", opacity: "0" },
          "10%": { opacity: "1" },
          "90%": { opacity: "1" },
          "100%": { transform: "translateX(200px) translateY(100px)", opacity: "0" },
        },
        "shooting-star-delayed": {
          "0%, 40%": { transform: "translateX(-80px) translateY(-40px)", opacity: "0" },
          "50%": { opacity: "1" },
          "90%": { opacity: "1" },
          "100%": { transform: "translateX(180px) translateY(90px)", opacity: "0" },
        },
        "orbit": {
          "0%": { transform: "rotate(0deg)" },
          "100%": { transform: "rotate(360deg)" },
        },
        "orbit-reverse": {
          "0%": { transform: "rotate(360deg)" },
          "100%": { transform: "rotate(0deg)" },
        },
        "bubble": {
          "0%": { transform: "translateY(0) scale(1)", opacity: "0.6" },
          "50%": { transform: "translateY(-50vh) scale(1.1)", opacity: "0.4" },
          "100%": { transform: "translateY(-100vh) scale(0.8)", opacity: "0" },
        },
        "bubble-delayed": {
          "0%, 20%": { transform: "translateY(0) scale(1)", opacity: "0" },
          "25%": { opacity: "0.5" },
          "75%": { transform: "translateY(-80vh) scale(1.05)", opacity: "0.3" },
          "100%": { transform: "translateY(-100vh) scale(0.9)", opacity: "0" },
        },
        "bubble-slow": {
          "0%": { transform: "translateY(0) scale(1)", opacity: "0.55" },
          "100%": { transform: "translateY(-100vh) scale(0.7)", opacity: "0" },
        },
        "dna-helix": {
          "0%, 100%": { transform: "translateY(0) rotateY(0deg)" },
          "50%": { transform: "translateY(-10px) rotateY(180deg)" },
        },
        "morph": {
          "0%, 100%": { borderRadius: "60% 40% 30% 70% / 60% 30% 70% 40%" },
          "25%": { borderRadius: "30% 60% 70% 40% / 50% 60% 30% 60%" },
          "50%": { borderRadius: "50% 60% 30% 60% / 30% 60% 70% 40%" },
          "75%": { borderRadius: "60% 40% 60% 30% / 70% 30% 50% 60%" },
        },
        "glitch": {
          "0%, 90%, 100%": { transform: "translate(0)" },
          "92%": { transform: "translate(-2px, 1px)" },
          "94%": { transform: "translate(2px, -1px)" },
          "96%": { transform: "translate(-1px, -1px)" },
          "98%": { transform: "translate(1px, 1px)" },
        },
        "typewriter": {
          "0%, 100%": { opacity: "0.5", transform: "translateX(0)" },
          "50%": { opacity: "0.8", transform: "translateX(3px)" },
        },
        "wave": {
          "0%": { transform: "translateX(-50px)" },
          "100%": { transform: "translateX(50px)" },
        },
        "wave-reverse": {
          "0%": { transform: "translateX(50px)" },
          "100%": { transform: "translateX(-50px)" },
        },
        "bounce-1": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-10px)" },
        },
        "bounce-2": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-10px)" },
        },
        "bounce-3": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-10px)" },
        },
        "cursor": {
          "0%, 100%": { transform: "translate(0, 0)" },
          "25%": { transform: "translate(10px, -5px)" },
          "50%": { transform: "translate(15px, 5px)" },
          "75%": { transform: "translate(5px, 10px)" },
        },
        "heartbeat-line": {
          "0%, 100%": { opacity: "0.5", transform: "scaleX(1)" },
          "50%": { opacity: "0.8", transform: "scaleX(1.05)" },
        },
        "twinkle": {
          "0%, 100%": { opacity: "0.75", transform: "scale(1)" },
          "50%": { opacity: "0.4", transform: "scale(0.8)" },
        },
        "fly-path": {
          "0%": { top: "15%", left: "-5%", transform: "rotate(-15deg)" },
          "25%": { top: "25%", left: "25%", transform: "rotate(10deg)" },
          "50%": { top: "40%", left: "55%", transform: "rotate(-5deg)" },
          "75%": { top: "30%", left: "80%", transform: "rotate(15deg)" },
          "100%": { top: "20%", left: "105%", transform: "rotate(-10deg)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.6s ease-out forwards",
        "slide-in-left": "slide-in-left 0.5s ease-out forwards",
        "slide-in-right": "slide-in-right 0.5s ease-out forwards",
        "pop-in": "pop-in 0.4s ease-out forwards",
        "bounce-in": "bounce-in 0.6s ease-out forwards",
        "spin-slow": "spin-slow 20s linear infinite",
        "spin-reverse": "spin-reverse 25s linear infinite",
        "pulse-glow": "pulse-glow 2s ease-in-out infinite",
        "float": "float 6s ease-in-out infinite",
        "float-rotate": "float-rotate 7s ease-in-out infinite",
        "float-delayed": "float-delayed 8s ease-in-out infinite",
        "pulse-float": "pulse-float 4s ease-in-out infinite",
        "wiggle-slow": "wiggle-slow 3s ease-in-out infinite",
        "heartbeat": "heartbeat 2s ease-in-out infinite",
        "bounce-horizontal": "bounce-horizontal 2s ease-in-out infinite",
        "flash": "flash 2s ease-in-out infinite",
        "bounce-slow": "bounce-slow 2.5s ease-in-out infinite",
        "bounce-elastic": "bounce-elastic 3s ease-in-out infinite",
        "fly": "fly 8s ease-in-out infinite",
        "steam": "steam 2s ease-in-out infinite",
        "draw-line": "draw-line 3s ease-out forwards",
        "draw-path": "draw-path 2s ease-out forwards",
        "wiggle": "wiggle 0.5s ease-in-out infinite",
        "shooting-star": "shooting-star 4s ease-in-out infinite",
        "shooting-star-delayed": "shooting-star-delayed 6s ease-in-out infinite",
        "orbit": "orbit 12s linear infinite",
        "orbit-reverse": "orbit-reverse 15s linear infinite",
        "bubble": "bubble 8s ease-in-out infinite",
        "bubble-delayed": "bubble-delayed 10s ease-in-out infinite",
        "bubble-slow": "bubble-slow 12s ease-in-out infinite",
        "dna-helix": "dna-helix 4s ease-in-out infinite",
        "morph": "morph 8s ease-in-out infinite",
        "glitch": "glitch 3s ease-in-out infinite",
        "typewriter": "typewriter 2s ease-in-out infinite",
        "wave": "wave 4s ease-in-out infinite alternate",
        "wave-reverse": "wave-reverse 5s ease-in-out infinite alternate",
        "bounce-1": "bounce-1 0.6s ease-in-out infinite",
        "bounce-2": "bounce-2 0.6s ease-in-out 0.1s infinite",
        "bounce-3": "bounce-3 0.6s ease-in-out 0.2s infinite",
        "cursor": "cursor 4s ease-in-out infinite",
        "heartbeat-line": "heartbeat-line 2s ease-in-out infinite",
        "twinkle": "twinkle 2s ease-in-out infinite",
        "fly-path": "fly-path 12s linear infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
